name: Release
on:
  push:
    tags:
      - '*'
permissions: write-all
jobs:  
  publish_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
      working-directory: ./02-MyDev/00/electron-app/
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run electron:build:win
      working-directory: ./02-MyDev/00/electron-app/
